version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: dev_atendimento_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15-alpine
    container_name: dev_atendimento_postgres
    restart: always
    environment:
      POSTGRES_DB: atendimento_db
      POSTGRES_USER: atendimento_user
      POSTGRES_PASSWORD: atendimento_pass
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
